
# Paths
HOME		= ./
VPATH		= $(HOME)src/
BIN		= $(HOME)bin/
#TEMP		= $(HOME)/temp/

# Programs
PRGS		= Parser.class

# default targets
.PHONY: all install

Parser.class:	$(VPATH)Parser.java
	javac -d $(BIN) $(VPATH)Parser.java


